### ISSUE TITLE
trubrics_utils

### ISSUE THREAD

**Issue by edwinjosechittilappilly** [trubrics/trubrics-sdk#86]
trubrics_utils Not found Error
Also the User Feedbacks are not updating in the Dashboard

**Comment by jeffkayne** [comment]
What version are you on? For feedback not being updated in the dashboard, it is generally caused because of how streamlit works. When you hit submit, the whole app is executed from top to bottom (like a regular button click in streamlit). It's only then that the component submit function is executed. This means that if your st_feeeback() function is inside an if statement that is false when the app is rerun, the component will disappear and the submit function to save feedback to Trubrics will never be executed
